const Name: string = "Go";
const Version: string = "1.16";
const ReleasedYear: number = 2009;
const TrueFlag: boolean = true;
const FalseFlag: boolean = false;
const a: number = 5;
const b: boolean = false;
let explicitInt: number = 10;
let implicitInt: number = 20;
let noValueInt: number;
let explicitBool: boolean = true;
let explicitString: string = "explicit";
let explicitArray: number[] = [1, 2, 3, 4, 5];
let implicitArray: number[] = [6, 7, 8, 9, 10];
let noValueArray: number[];
let intVar: number = 5;
let boolVar: boolean = false;
let stringVar: string = "hello";
let uninitString: string;
let boolArrayVar: boolean[] = [true, false];
let arr: number[] = [1, 2, 3, 4, 5];
let uninitIntArray: number[];
